name: mig_screens
description: MIG screen-only Flutter build.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/screens/movies-home.jpg
    - assets/screens/series-detail.jpg
    - assets/screens/episodes.jpg
    - assets/screens/movie-detail.jpg
    - assets/screens/season-detail.jpg
    - assets/screens/episode-detail.jpg
    - assets/screens/live-tv.jpg
    - assets/screens/downloads.jpg
    - assets/screens/player.jpg
  fonts:
    - family: Figtree
      fonts:
        - asset: assets/fonts/Figtree/Figtree-Medium.ttf
        - asset: assets/fonts/Figtree/Figtree-Bold.ttf